-- Migration: V1.2.0__create_employee_table.sql
-- Description: Create EMPLOYEE table in BRONZE_DB.RAW schema
-- Created: $(date)

CREATE TABLE BRONZE_DB.RAW.EMPLOYEE
(
   EMPLOYEE_ID NUMBER
  ,FIRST_NAME VARCHAR(100)
  ,LAST_NAME VARCHAR(100)
  ,EMAIL VARCHAR(255)
  ,DEPARTMENT VARCHAR(50)
  ,SALARY NUMBER(10,2)
  ,HIRE_DATE DATE
  ,IS_ACTIVE BOOLEAN DEFAULT TRUE
);

-- Add MANAGE column
ALTER TABLE BRONZE_DB.RAW.EMPLOYEE
ADD COLUMN MANAGE VARCHAR(100);


