-- Migration: V1.3.2__create_silver_dynamic_table.sql
-- Description: Create dynamic table in SILVER schema based on BRONZE.SALES
-- Created: $(date)

-- Create dynamic table in SILVER schema
CREATE OR REPLACE DYNAMIC TABLE DEMO_SCHEMA_DRIFT.SILVER.SALES_CLEANED
TARGET_LAG = DOWNSTREAM
WAREHOUSE = 'DEVOPS_WH'
AS
SELECT 
    SALE_ID,
    PRODUCT_NAME,
    QUANTITY,
    UNIT_PRICE,
    SALE_DATE,
    CURRENT_TIMESTAMP() AS PROCESSED_AT
FROM DEMO_SCHEMA_DRIFT.BRONZE.SALES
WHERE SALE_ID IS NOT NULL
  AND PRODUCT_NAME IS NOT NULL
  AND QUANTITY > 0
  AND UNIT_PRICE > 0;
