-- Migration: V1.3.3__create_gold_dynamic_table.sql
-- Description: Create deduplicated dynamic table in GOLD schema
-- Created: $(date)

-- Create deduplicated dynamic table in GOLD schema
CREATE OR REPLACE DYNAMIC TABLE DEMO_SCHEMA_DRIFT.GOLD.SALES_AGGREGATED
TARGET_LAG = '5 minutes'
WAREHOUSE = 'DEVOPS_WH'
AS
SELECT 
    PRODUCT_NAME,
    COUNT(*) AS TOTAL_SALES,
    SUM(QUANTITY) AS TOTAL_QUANTITY,
    SUM(UNIT_PRICE * QUANTITY) AS TOTAL_REVENUE,
    AVG(UNIT_PRICE) AS AVG_UNIT_PRICE,
    MAX(SALE_DATE) AS LAST_SALE_DATE,
    CURRENT_TIMESTAMP() AS AGGREGATED_AT
FROM DEMO_SCHEMA_DRIFT.SILVER.SALES_CLEANED
GROUP BY PRODUCT_NAME;
