name: 'Terraform Cloud Deploy'

on:
  push:
    branches: [ main ]
    paths:
      - 'workspace_cicd_snowflake/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'workspace_cicd_snowflake/**'

env:
  TF_CLI_ARGS: '-chdir=workspace_cicd_snowflake'

jobs:
  plan-and-validate:
    name: 'Plan and Validate'
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.3

    - name: Terraform Format Check
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -out=tfplan
      continue-on-error: true

    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v4
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      with:
        name: terraform-plan
        path: workspace_cicd_snowflake/tfplan
        retention-days: 1

  apply:
    name: 'Apply'
    runs-on: ubuntu-latest
    needs: plan-and-validate
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.3

    - name: Download Plan Artifact
      uses: actions/download-artifact@v4
      with:
        name: terraform-plan
        path: workspace_cicd_snowflake/

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
